"""clientes digito_verificacion

Revision ID: 18e6c803f9ee
Revises: fe57f68e9db9
Create Date: 2026-09-09 21:40:31.192542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e6c803f9ee'
down_revision: Union[str, None] = 'fe57f68e9db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('digito_verificacion', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'digito_verificacion')
    # ### end Alembic commands ###
