"""compras_cufe

Revision ID: 221b2074d216
Revises: c2995368d397
Create Date: 2026-09-16 00:04:20.340282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221b2074d216'
down_revision: Union[str, None] = 'c2995368d397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compras', sa.Column('cufe', sa.String(length=200), nullable=True))
    op.create_index('ix_compras_empresa_cufe_activo', 'compras', ['empresa_id', 'cufe'], unique=True, postgresql_where=sa.text('eliminado IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_compras_empresa_cufe_activo', table_name='compras', postgresql_where=sa.text('eliminado IS NULL'))
    op.drop_column('compras', 'cufe')
    # ### end Alembic commands ###
