"""empleados_terceros_nomina

Revision ID: 2292dc132491
Revises: 481b6f0aa478
Create Date: 2026-09-23 11:17:29.298711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2292dc132491'
down_revision: Union[str, None] = '481b6f0aa478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=2), nullable=False),
    sa.Column('numero_documento', sa.String(length=60), nullable=False),
    sa.Column('primer_apellido', sa.String(length=60), nullable=False),
    sa.Column('segundo_apellido', sa.String(length=60), nullable=True),
    sa.Column('primer_nombre', sa.String(length=60), nullable=False),
    sa.Column('otros_nombres', sa.String(length=60), nullable=True),
    sa.Column('tipo_trabajador', sa.String(length=2), nullable=False),
    sa.Column('subtipo_trabajador', sa.String(length=2), nullable=False),
    sa.Column('alto_riesgo_pension', sa.Boolean(), nullable=False),
    sa.Column('salario_integral', sa.Boolean(), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=2), nullable=False),
    sa.Column('sueldo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('codigo_trabajador', sa.String(length=50), nullable=True),
    sa.Column('lugar_trabajo_pais', sa.String(length=2), nullable=False),
    sa.Column('lugar_trabajo_municipio', sa.String(length=5), nullable=False),
    sa.Column('lugar_trabajo_direccion', sa.String(length=300), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('tipo_cuenta', sa.String(length=30), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=True),
    sa.Column('correo_electronico', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_retiro', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_empleados_empresa_documento_activo', 'empleados', ['empresa_id', 'tipo_documento', 'numero_documento'], unique=True, postgresql_where=sa.text('eliminado IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_empleados_empresa_documento_activo', table_name='empleados', postgresql_where=sa.text('eliminado IS NULL'))
    op.drop_table('empleados')
    # ### end Alembic commands ###
