"""factura_lineas codigo

Revision ID: 2a91d9288fb6
Revises: 802002b30e04
Create Date: 2026-09-01 14:09:23.589673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a91d9288fb6'
down_revision: Union[str, None] = '802002b30e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factura_lineas', sa.Column('codigo', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factura_lineas', 'codigo')
    # ### end Alembic commands ###
