"""clientes regimen_fiscal

Revision ID: 2afbde1450b1
Revises: 2a91d9288fb6
Create Date: 2026-09-01 16:40:30.975572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2afbde1450b1'
down_revision: Union[str, None] = '2a91d9288fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('regimen_fiscal', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'regimen_fiscal')
    # ### end Alembic commands ###
