"""empresas notificacion_correo y tabla suscripciones

Revision ID: 2e2191b320bf
Revises: 358d960f1e4c
Create Date: 2026-08-30 22:24:26.316425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2191b320bf'
down_revision: Union[str, None] = '358d960f1e4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suscripciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('max_documentos', sa.Integer(), nullable=False),
    sa.Column('documentos_usados', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Una sola suscripcion activa por empresa -- blindado a nivel de DB para que
    # dos "cambiar plan" casi simultaneos no puedan crear dos filas activas.
    op.create_index(
        'ix_suscripciones_empresa_activa',
        'suscripciones',
        ['empresa_id'],
        unique=True,
        postgresql_where=sa.text("estado = 'activa'"),
    )
    op.add_column(
        'empresas',
        sa.Column('notificacion_correo', sa.Boolean(), nullable=False, server_default=sa.text('true')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'notificacion_correo')
    op.drop_index('ix_suscripciones_empresa_activa', table_name='suscripciones')
    op.drop_table('suscripciones')
    # ### end Alembic commands ###
