"""resolucion dian

Revision ID: 4616657cdfc8
Revises: 0ba789b283cc
Create Date: 2026-08-31 15:37:36.519850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4616657cdfc8'
down_revision: Union[str, None] = '0ba789b283cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resoluciones_dian',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('numero_resolucion', sa.String(length=50), nullable=False),
    sa.Column('prefijo', sa.String(length=10), nullable=False),
    sa.Column('rango_minimo', sa.Integer(), nullable=False),
    sa.Column('rango_maximo', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('technical_key', sa.String(length=100), nullable=False),
    sa.Column('consecutivo_actual', sa.Integer(), nullable=False),
    sa.Column('estado_validacion', sa.String(length=20), nullable=False),
    sa.Column('mensaje_validacion', sa.String(length=500), nullable=True),
    sa.Column('fecha_ultima_validacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resoluciones_dian')
    # ### end Alembic commands ###
