"""productos e impuestos empresa

Revision ID: 4a41825a727d
Revises: a912097f0292
Create Date: 2026-08-31 22:44:44.323391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a41825a727d'
down_revision: Union[str, None] = 'a912097f0292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impuestos_empresa',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tributo', sa.String(length=50), nullable=False),
    sa.Column('tarifa', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('tarifa >= 0 AND tarifa <= 100', name='ck_impuestos_empresa_tarifa_rango'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_impuestos_empresa_empresa_preset_activo', 'impuestos_empresa', ['empresa_id', 'tributo', 'tarifa'], unique=True, postgresql_where=sa.text('eliminado IS NULL'))
    op.create_table('productos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('tributo', sa.String(length=50), nullable=True),
    sa.Column('tarifa_impuesto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("tipo IN ('bien', 'servicio')", name='ck_productos_tipo'),
    sa.CheckConstraint('precio >= 0', name='ck_productos_precio_positivo'),
    sa.CheckConstraint('tarifa_impuesto >= 0 AND tarifa_impuesto <= 100', name='ck_productos_tarifa_impuesto_rango'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_productos_empresa_codigo_activo', 'productos', ['empresa_id', 'codigo'], unique=True, postgresql_where=sa.text('eliminado IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_productos_empresa_codigo_activo', table_name='productos', postgresql_where=sa.text('eliminado IS NULL'))
    op.drop_table('productos')
    op.drop_index('ix_impuestos_empresa_empresa_preset_activo', table_name='impuestos_empresa', postgresql_where=sa.text('eliminado IS NULL'))
    op.drop_table('impuestos_empresa')
    # ### end Alembic commands ###
