"""factura_lineas unidad_medida

Revision ID: 59afceecbed2
Revises: 8028446938b6
Create Date: 2026-09-01 09:10:53.060964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59afceecbed2'
down_revision: Union[str, None] = '8028446938b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factura_lineas', sa.Column('unidad_medida', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('factura_lineas', 'unidad_medida')
    # ### end Alembic commands ###
