"""facturas firma_digital

Revision ID: 802002b30e04
Revises: 90d5e356d0a0
Create Date: 2026-09-01 11:32:09.431870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802002b30e04'
down_revision: Union[str, None] = '90d5e356d0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('firma_digital', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'firma_digital')
    # ### end Alembic commands ###
