"""facturas y factura_lineas

Revision ID: 8028446938b6
Revises: 4a41825a727d
Create Date: 2026-09-01 09:06:02.582531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8028446938b6'
down_revision: Union[str, None] = '4a41825a727d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('consecutivo', sa.Integer(), nullable=True),
    sa.Column('numero_completo', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_impuestos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('forma_pago', sa.String(length=10), nullable=True),
    sa.Column('metodo_pago', sa.String(length=10), nullable=True),
    sa.Column('alegra_invoice_id', sa.String(length=50), nullable=True),
    sa.Column('cufe', sa.String(length=200), nullable=True),
    sa.Column('razon_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('borrador', 'enviada', 'aceptada', 'rechazada')", name='ck_facturas_estado'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura_lineas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tributo', sa.String(length=50), nullable=True),
    sa.Column('tarifa_impuesto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('impuesto_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_factura_lineas_cantidad_positiva'),
    sa.CheckConstraint('precio_unitario >= 0', name='ck_factura_lineas_precio_no_negativo'),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('factura_lineas')
    op.drop_table('facturas')
    # ### end Alembic commands ###
