"""facturas recibidas y eventos del receptor

Revision ID: 8d59ff2c4e92
Revises: eeac61931003
Create Date: 2026-09-15 15:12:51.752484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d59ff2c4e92'
down_revision: Union[str, None] = 'eeac61931003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facturas_recibidas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.Column('cufe', sa.String(length=200), nullable=False),
    sa.Column('numero_documento_proveedor', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_facturas_recibidas_empresa_cufe_activo', 'facturas_recibidas', ['empresa_id', 'cufe'], unique=True, postgresql_where=sa.text('eliminado IS NULL'))
    op.create_table('eventos_receptor',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('factura_recibida_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=3), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('legal_status', sa.String(length=30), nullable=True),
    sa.Column('cude', sa.String(length=200), nullable=True),
    sa.Column('claim_code', sa.String(length=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('generador_tipo_identificacion', sa.String(length=20), nullable=True),
    sa.Column('generador_numero_identificacion', sa.String(length=50), nullable=True),
    sa.Column('generador_dv', sa.String(length=1), nullable=True),
    sa.Column('generador_nombres', sa.String(length=150), nullable=True),
    sa.Column('generador_apellidos', sa.String(length=150), nullable=True),
    sa.Column('generador_cargo', sa.String(length=150), nullable=True),
    sa.Column('razon_rechazo', sa.Text(), nullable=True),
    sa.Column('notificaciones_dian', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tipo IN ('030', '031', '032', '033', '034')", name='ck_eventos_receptor_tipo'),
    sa.ForeignKeyConstraint(['factura_recibida_id'], ['facturas_recibidas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos_receptor')
    op.drop_index('ix_facturas_recibidas_empresa_cufe_activo', table_name='facturas_recibidas', postgresql_where=sa.text('eliminado IS NULL'))
    op.drop_table('facturas_recibidas')
    # ### end Alembic commands ###
