"""facturas qr_code_content

Revision ID: 90d5e356d0a0
Revises: 59afceecbed2
Create Date: 2026-09-01 11:06:10.950430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d5e356d0a0'
down_revision: Union[str, None] = '59afceecbed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('qr_code_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'qr_code_content')
    # ### end Alembic commands ###
