"""habilitaciones_dian

Revision ID: 9c9b778bc4ba
Revises: f27f184337d8
Create Date: 2026-09-28 10:53:26.280229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c9b778bc4ba'
down_revision: Union[str, None] = 'f27f184337d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilitaciones_dian',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('test_set_id', sa.String(length=36), nullable=True),
    sa.Column('alegra_test_set_id', sa.String(length=50), nullable=True),
    sa.Column('estado_set_pruebas', sa.String(length=20), nullable=True),
    sa.Column('errores_set_pruebas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_envio_set_pruebas', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'tipo', name='uq_habilitaciones_dian_empresa_tipo')
    )
    # ### end Alembic commands ###
    # Sin backfill a proposito: la fuente de verdad es governmentStatus en
    # Alegra y HabilitacionDianService la consulta en el primer envio (o al
    # abrir la pantalla), asi las empresas ya habilitadas no se bloquean.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habilitaciones_dian')
    # ### end Alembic commands ###
