"""facturas notificaciones_dian

Revision ID: a3a0a0224609
Revises: 2afbde1450b1
Create Date: 2026-09-02 10:49:02.493883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3a0a0224609'
down_revision: Union[str, None] = '2afbde1450b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facturas', sa.Column('notificaciones_dian', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facturas', 'notificaciones_dian')
    # ### end Alembic commands ###
