"""notas_credito y anular factura

Revision ID: a619403ac017
Revises: a3a0a0224609
Create Date: 2026-09-02 23:52:02.040113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a619403ac017'
down_revision: Union[str, None] = 'a3a0a0224609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consecutivos_notas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('consecutivo_actual', sa.Integer(), nullable=False),
    sa.CheckConstraint("tipo IN ('credito', 'debito')", name='ck_consecutivos_notas_tipo'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'tipo', name='uq_consecutivos_notas_empresa_tipo')
    )
    op.create_table('notas_credito',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo_codigo', sa.String(length=5), nullable=False),
    sa.Column('consecutivo', sa.Integer(), nullable=True),
    sa.Column('numero_completo', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_impuestos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('alegra_credit_note_id', sa.String(length=50), nullable=True),
    sa.Column('cude', sa.String(length=200), nullable=True),
    sa.Column('qr_code_content', sa.Text(), nullable=True),
    sa.Column('razon_rechazo', sa.Text(), nullable=True),
    sa.Column('notificaciones_dian', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('borrador', 'enviada', 'aceptada', 'rechazada')", name='ck_notas_credito_estado'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_credito_lineas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nota_credito_id', sa.UUID(), nullable=False),
    sa.Column('factura_linea_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tributo', sa.String(length=50), nullable=True),
    sa.Column('tarifa_impuesto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('impuesto_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_nota_credito_lineas_cantidad_positiva'),
    sa.ForeignKeyConstraint(['factura_linea_id'], ['factura_lineas.id'], ),
    sa.ForeignKeyConstraint(['nota_credito_id'], ['notas_credito.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # No autogenerado -- Alembic no detecta cambios de CheckConstraint por
    # defecto. Agrega el estado nuevo "anulada" (factura 100% acreditada por
    # notas credito, ver NotaCreditoService._revisar_anulacion).
    op.drop_constraint('ck_facturas_estado', 'facturas', type_='check')
    op.create_check_constraint(
        'ck_facturas_estado', 'facturas',
        "estado IN ('borrador', 'enviada', 'aceptada', 'rechazada', 'anulada')",
    )


def downgrade() -> None:
    op.drop_constraint('ck_facturas_estado', 'facturas', type_='check')
    op.create_check_constraint(
        'ck_facturas_estado', 'facturas',
        "estado IN ('borrador', 'enviada', 'aceptada', 'rechazada')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nota_credito_lineas')
    op.drop_table('notas_credito')
    op.drop_table('consecutivos_notas')
    # ### end Alembic commands ###
