"""resoluciones documento soporte estado validacion

Revision ID: bdeb372c86c4
Revises: 9c9b778bc4ba
Create Date: 2026-09-28 16:58:39.131796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdeb372c86c4'
down_revision: Union[str, None] = '9c9b778bc4ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resoluciones_documento_soporte', sa.Column('estado_validacion', sa.String(length=20), server_default='pendiente', nullable=False))
    op.add_column('resoluciones_documento_soporte', sa.Column('mensaje_validacion', sa.String(length=500), nullable=True))
    op.add_column('resoluciones_documento_soporte', sa.Column('fecha_ultima_validacion', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resoluciones_documento_soporte', 'fecha_ultima_validacion')
    op.drop_column('resoluciones_documento_soporte', 'mensaje_validacion')
    op.drop_column('resoluciones_documento_soporte', 'estado_validacion')
    # ### end Alembic commands ###
