"""documento_soporte_resolucion_y_direccion_proveedor

Revision ID: c2995368d397
Revises: 8d59ff2c4e92
Create Date: 2026-09-15 18:01:13.250201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2995368d397'
down_revision: Union[str, None] = '8d59ff2c4e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resoluciones_documento_soporte',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('numero_resolucion', sa.String(length=50), nullable=False),
    sa.Column('prefijo', sa.String(length=10), nullable=False),
    sa.Column('rango_minimo', sa.Integer(), nullable=False),
    sa.Column('rango_maximo', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('consecutivo_actual', sa.Integer(), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('documentos_soporte',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('proveedor_id', sa.UUID(), nullable=False),
    sa.Column('compra_id', sa.UUID(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('consecutivo', sa.Integer(), nullable=True),
    sa.Column('numero_completo', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_impuestos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('forma_pago', sa.String(length=10), nullable=True),
    sa.Column('metodo_pago', sa.String(length=10), nullable=True),
    sa.Column('alegra_support_document_id', sa.String(length=50), nullable=True),
    sa.Column('cuds', sa.String(length=200), nullable=True),
    sa.Column('qr_code_content', sa.Text(), nullable=True),
    sa.Column('razon_rechazo', sa.Text(), nullable=True),
    sa.Column('notificaciones_dian', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('borrador', 'enviado', 'aceptado', 'rechazado')", name='ck_documentos_soporte_estado'),
    sa.ForeignKeyConstraint(['compra_id'], ['compras.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_soporte_lineas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('documento_soporte_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tributo', sa.String(length=50), nullable=True),
    sa.Column('tarifa_impuesto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('impuesto_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_documento_soporte_lineas_cantidad_positiva'),
    sa.CheckConstraint('precio_unitario >= 0', name='ck_documento_soporte_lineas_precio_no_negativo'),
    sa.ForeignKeyConstraint(['documento_soporte_id'], ['documentos_soporte.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('proveedores', sa.Column('direccion', sa.String(length=300), nullable=True))
    op.add_column('proveedores', sa.Column('departamento', sa.String(length=2), nullable=True))
    op.add_column('proveedores', sa.Column('municipio', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proveedores', 'municipio')
    op.drop_column('proveedores', 'departamento')
    op.drop_column('proveedores', 'direccion')
    op.drop_table('documento_soporte_lineas')
    op.drop_table('documentos_soporte')
    op.drop_table('resoluciones_documento_soporte')
    # ### end Alembic commands ###
