"""nomina_electronica

Revision ID: ec9e41b3aee3
Revises: 2292dc132491
Create Date: 2026-09-23 11:39:24.106250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec9e41b3aee3'
down_revision: Union[str, None] = '2292dc132491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consecutivos_nomina',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('consecutivo_actual', sa.Integer(), nullable=False),
    sa.CheckConstraint("tipo IN ('nomina', 'anulacion')", name='ck_consecutivos_nomina_tipo'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'tipo', name='uq_consecutivos_nomina_empresa_tipo')
    )
    op.create_table('nominas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('empleado_id', sa.UUID(), nullable=False),
    sa.Column('periodo_nomina', sa.String(length=2), nullable=False),
    sa.Column('fecha_liquidacion_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_liquidacion_fin', sa.Date(), nullable=False),
    sa.Column('fecha_pago', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forma_pago', sa.String(length=10), nullable=False),
    sa.Column('metodo_pago', sa.String(length=10), nullable=False),
    sa.Column('banco', sa.String(length=100), nullable=True),
    sa.Column('tipo_cuenta', sa.String(length=30), nullable=True),
    sa.Column('numero_cuenta', sa.String(length=50), nullable=True),
    sa.Column('devengados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deducciones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('devengados_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deducciones_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('comprobante_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('empleado_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('consecutivo', sa.Integer(), nullable=True),
    sa.Column('numero_completo', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('alegra_payroll_id', sa.String(length=50), nullable=True),
    sa.Column('cune', sa.String(length=200), nullable=True),
    sa.Column('qr_code_content', sa.Text(), nullable=True),
    sa.Column('firma_digital', sa.Text(), nullable=True),
    sa.Column('razon_rechazo', sa.Text(), nullable=True),
    sa.Column('notificaciones_dian', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutivo_anulacion', sa.Integer(), nullable=True),
    sa.Column('numero_completo_anulacion', sa.String(length=30), nullable=True),
    sa.Column('cune_anulacion', sa.String(length=200), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('borrador', 'enviada', 'aceptada', 'rechazada', 'anulada')", name='ck_nominas_estado'),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleados.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nominas')
    op.drop_table('consecutivos_nomina')
    # ### end Alembic commands ###
