"""inventario opcional: toggles empresa, stock en productos, movimientos

Revision ID: eeac61931003
Revises: f532576ecb2e
Create Date: 2026-09-15 10:52:48.443501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeac61931003'
down_revision: Union[str, None] = 'f532576ecb2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos_inventario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('origen_tipo', sa.String(length=20), nullable=False),
    sa.Column('origen_id', sa.UUID(), nullable=True),
    sa.Column('saldo_resultante', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("origen_tipo IN ('compra', 'factura', 'ajuste_manual')", name='ck_movimientos_inventario_origen_tipo'),
    sa.CheckConstraint("tipo IN ('entrada', 'salida')", name='ck_movimientos_inventario_tipo'),
    sa.CheckConstraint('cantidad > 0', name='ck_movimientos_inventario_cantidad_positiva'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'empresas',
        sa.Column('inventario_habilitado', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    op.add_column(
        'empresas',
        sa.Column('permitir_facturar_sin_stock', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    op.add_column('productos', sa.Column('stock_actual', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'stock_actual')
    op.drop_column('empresas', 'permitir_facturar_sin_stock')
    op.drop_column('empresas', 'inventario_habilitado')
    op.drop_table('movimientos_inventario')
    # ### end Alembic commands ###
