"""nomina_fecha_anulacion

Revision ID: f27f184337d8
Revises: 5aeb716a316b
Create Date: 2026-09-24 16:22:51.101486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27f184337d8'
down_revision: Union[str, None] = '5aeb716a316b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nominas', sa.Column('fecha_anulacion', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Nominas ya anuladas: una nomina anulada no se puede volver a editar, asi
    # que su ultima modificacion (actualizado) es el momento de la anulacion.
    op.execute(
        "UPDATE nominas SET fecha_anulacion = actualizado "
        "WHERE estado = 'anulada' AND consecutivo_anulacion IS NOT NULL AND fecha_anulacion IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nominas', 'fecha_anulacion')
    # ### end Alembic commands ###
