"""empresas regimen_fiscal

Revision ID: fe57f68e9db9
Revises: 468607b1011f
Create Date: 2026-09-09 16:29:59.969469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe57f68e9db9'
down_revision: Union[str, None] = '468607b1011f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('regimen_fiscal', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'regimen_fiscal')
    # ### end Alembic commands ###
