"""notas_debito y firma_digital en notas_credito

Revision ID: ff7b14743998
Revises: a619403ac017
Create Date: 2026-09-04 23:16:12.819116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff7b14743998'
down_revision: Union[str, None] = 'a619403ac017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas_debito',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('factura_id', sa.UUID(), nullable=False),
    sa.Column('cliente_id', sa.UUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('motivo_codigo', sa.String(length=5), nullable=False),
    sa.Column('consecutivo', sa.Integer(), nullable=True),
    sa.Column('numero_completo', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_impuestos', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('alegra_debit_note_id', sa.String(length=50), nullable=True),
    sa.Column('cude', sa.String(length=200), nullable=True),
    sa.Column('qr_code_content', sa.Text(), nullable=True),
    sa.Column('firma_digital', sa.Text(), nullable=True),
    sa.Column('razon_rechazo', sa.Text(), nullable=True),
    sa.Column('notificaciones_dian', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('eliminado', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('borrador', 'enviada', 'aceptada', 'rechazada')", name='ck_notas_debito_estado'),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['factura_id'], ['facturas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nota_debito_lineas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nota_debito_id', sa.UUID(), nullable=False),
    sa.Column('factura_linea_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tributo', sa.String(length=50), nullable=True),
    sa.Column('tarifa_impuesto', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('impuesto_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_linea', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('creado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cantidad > 0', name='ck_nota_debito_lineas_cantidad_positiva'),
    sa.ForeignKeyConstraint(['factura_linea_id'], ['factura_lineas.id'], ),
    sa.ForeignKeyConstraint(['nota_debito_id'], ['notas_debito.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('notas_credito', sa.Column('firma_digital', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas_credito', 'firma_digital')
    op.drop_table('nota_debito_lineas')
    op.drop_table('notas_debito')
    # ### end Alembic commands ###
